# Generated by Django 5.1.2 on 2024-11-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=100, verbose_name='Текст комментария'),
        ),
    ]
