# Generated by Django 5.1.2 on 2024-10-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_article_options_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeoncomment',
            unique_together={('author', 'comment')},
        ),
    ]
