    # Generated by Django 5.1.2 on 2024-10-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_likeoncomment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='count_of_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='likeoncomment',
            name='reaction',
            field=models.CharField(choices=[('&#128077;', 'like'), ('&#128557;', 'cry'), ('&#128562;', 'surprise'), ('&#128514;', 'laugh'), ('&#129505;', 'heart')], max_length=50, verbose_name='Текстовый код эмоции'),
        ),
    ]
